name: qbittorrent-tracker-add

services:
  qbittorrent-tracker-add:
    build: .
    environment:
      QBITTORRENT_ENDPOINT: "${QBITTORRENT_ENDPOINT}"
      QBITTORRENT_USERNAME: "${QBITTORRENT_USERNAME}"
      QBITTORRENT_PASSWORD: "${QBITTORRENT_PASSWORD}"
      INTERVAL: "${INTERVAL:-at 4:00 am}"
      TRACKER_LIST: "${TRACKER_LIST:-https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt}"
      TZ: "America/New_York"